#!/usr/bin/env python3
# Embeds every assets/shaders/*.{vert,frag} file into a generated C++ header as a
# string literal, so the GL renderer can run when the assets/ directory is absent
# (see issue #236). readFileAsString() falls back to these copies when a shader
# file is not found on disk, keyed by file name.
#
# Usage: generate_embedded_shaders.py <shaders_dir> <output_header>

import os
import sys


def pick_delimiter(text):
    # Raw-string delimiter that cannot appear in the shader source.
    base = "EMBEDDEDSHADER"
    delim = base
    suffix = 0
    while (")" + delim + '"') in text:
        suffix += 1
        delim = base + str(suffix)
    return delim


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: generate_embedded_shaders.py <shaders_dir> <output_header>\n")
        return 1

    shaders_dir = sys.argv[1]
    output_header = sys.argv[2]

    shaders = []
    if os.path.isdir(shaders_dir):
        for name in sorted(os.listdir(shaders_dir)):
            if name.endswith(".vert") or name.endswith(".frag"):
                with open(os.path.join(shaders_dir, name), "r", encoding="utf-8") as f:
                    shaders.append((name, f.read()))

    os.makedirs(os.path.dirname(output_header), exist_ok=True)

    out = []
    out.append("// Auto-generated by dinput_hook/generate_embedded_shaders.py -- DO NOT EDIT.")
    out.append("// Embeds assets/shaders/*.{vert,frag} so the GL renderer can run without the")
    out.append("// assets/ directory present (issue #236). Keyed by file name.")
    out.append("#pragma once")
    out.append("")
    out.append("#include <cstring>")
    out.append("")
    out.append("namespace embedded_shaders {")
    out.append("")
    out.append("struct EmbeddedShader {")
    out.append("    const char *name;")
    out.append("    const char *source;")
    out.append("};")
    out.append("")
    out.append("inline const EmbeddedShader kEmbeddedShaders[] = {")
    for name, text in shaders:
        delim = pick_delimiter(text)
        out.append('    {"%s", R"%s(%s)%s"},' % (name, delim, text, delim))
    out.append("};")
    out.append("")
    out.append("// Returns the embedded source for a shader file name, or nullptr if not embedded.")
    out.append("inline const char *find(const char *name) {")
    out.append("    for (const EmbeddedShader &s : kEmbeddedShaders) {")
    out.append("        if (std::strcmp(s.name, name) == 0) {")
    out.append("            return s.source;")
    out.append("        }")
    out.append("    }")
    out.append("    return nullptr;")
    out.append("}")
    out.append("")
    out.append("}  // namespace embedded_shaders")
    out.append("")

    with open(output_header, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))

    return 0


if __name__ == "__main__":
    sys.exit(main())
