#include "globals.h"

#include "types.h"
#include "types_directx.h"

// This file is auto-generated by scripts/GenerateGlobalHeaderFromSymbols.py and data_symbols.syms
// using Jinja template globals.h.j2

// Line 0: diDataFormat 0x0049e720 _DIDATAFORMAT
_DIDATAFORMAT diDataFormat ;

// Line 2: A3dApi_GUID 0x004ae0e8 GUID
GUID A3dApi_GUID ;

// Line 3: IID_Ia3d4_GUID 0x004ae128 GUID
GUID IID_Ia3d4_GUID ;

// Line 4: IID_IA3dListener_GUID 0x004ae158 GUID
GUID IID_IA3dListener_GUID ;

// Line 6: iDirectDraw4_GUID 0x004af1c8 GUID
GUID iDirectDraw4_GUID ;

// Line 7: iDirect3D3_GUID 0x004af278 GUID
GUID iDirect3D3_GUID ;

// Line 9: IID_IDirectPlay4_GUID 0x004af4a8 GUID
GUID IID_IDirectPlay4_GUID ;

// Line 10: DirectPlay_GUID 0x004af4c8 GUID
GUID DirectPlay_GUID ;

// Line 12: Window_UUID 0x004af9b0 uint32_t[4] = { 0xC95FB584, 0x11D2FA31, 0xAA009D90, 0xAD22A300 }
uint32_t Window_UUID[4]   = { 0xC95FB584, 0x11D2FA31, 0xAA009D90, 0xAD22A300 };

// Line 14: rdMatrix34_identity 0x004af880 rdMatrix34 = {{1.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}
rdMatrix34  rdMatrix34_identity  = {{1.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}};

// Line 16: Main_force_feedback 0x004b4938 int = 1
int  Main_force_feedback  = 1;

// Line 17: Main_nut_delay_ms 0x004b6718 int = 32
int  Main_nut_delay_ms  = 32;

// Line 18: Main_sound 0x004b6d20 int = 1
int  Main_sound  = 1;

// Line 19: Main_sound_unk 0x004b6d2c int = 1
int  Main_sound_unk  = 1;

// Line 20: Main_fullscreen_unk 0x004b79f8 int = 1
int  Main_fullscreen_unk  = 1;

// Line 21: Main_display_intro_scene 0x004b7a00 int = 1
int  Main_display_intro_scene  = 1;

// Line 23: swrSound_criticalSection 0x004b7e7e LPCRITICAL_SECTION
LPCRITICAL_SECTION swrSound_criticalSection ;

// Line 25: Main_sound_3dimpact 0x004c7aa8 int = -1
int  Main_sound_3dimpact  = -1;

// Line 26: Main_sound_doppler_scale 0x004c7d74 float = 1.0
float  Main_sound_doppler_scale  = 1.0;

// Line 27: Main_sound_rolloff 0x004c7d78 float = 0.15
float  Main_sound_rolloff  = 0.15;

// Line 29: rdMatrixStack34_modified 0x004c3c0c int
int rdMatrixStack34_modified ;

// Line 31: swrRace_AILevel 0x004c707c int
int swrRace_AILevel ;

// Line 33: swrRace_DeathSpeedMin 0x004c7bb8 float = 325.00
float  swrRace_DeathSpeedMin  = 325.00;

// Line 34: swrRace_DeathSpeedDrop 0x004c7bbc float = 140.0
float  swrRace_DeathSpeedDrop  = 140.0;

// Line 36: swrRace_FireTimer 0x004c7bc0 float = -1.0
float  swrRace_FireTimer  = -1.0;

// Line 38: stdMath_SinTable 0x004c98e8 float[4096]
float stdMath_SinTable[4096] ;

// Line 39: stdMath_TanTable 0x004cd8e8 float[4096]
float stdMath_TanTable[4096] ;

// Line 41: wuRegistry_lpClass 0x004d55cc LPSTR
LPSTR wuRegistry_lpClass ;

// Line 43: multiplayer_enabled 0x004d5e00 int
int multiplayer_enabled ;

// Line 45: swrText_keyNameText 0x004d5f38 char[128]
char swrText_keyNameText[128] ;

// Line 47: rdLight_1 0x004d6b78 rdLight
rdLight rdLight_1 ;

// Line 48: rdLight_2 0x004d6ba8 rdLight
rdLight rdLight_2 ;

// Line 50: directDrawSurface4_ptr2 0x004d6be0 LPDIRECTDRAWSURFACE4
LPDIRECTDRAWSURFACE4 directDrawSurface4_ptr2 ;

// Line 51: ddSurfaceDesc_2 0x004d6be4 _DDSURFACEDESC
_DDSURFACEDESC ddSurfaceDesc_2 ;

// Line 53: time_buffer 0x004e9f20 char[256]
char time_buffer[256] ;

// Line 56: sync_timer_ms 0x004eb230 int
int sync_timer_ms ;

// Line 58: playerNumber 0x004eb3b4 int
int playerNumber ;

// Line 60: swrText_racerTab_array 0x004eb3c4 char**
char** swrText_racerTab_array ;

// Line 61: swrText_racerTab_buffer 0x004eb3c8 char*
char* swrText_racerTab_buffer ;

// Line 63: swrText_nbLinesRacerTab 0x004eb3cc int
int swrText_nbLinesRacerTab ;

// Line 65: ia3dSourceThreadId 0x004eb3f8 DWORD
DWORD ia3dSourceThreadId ;

// Line 66: ia3dSourceEventHandle 0x004eb3fc HANDLE
HANDLE ia3dSourceEventHandle ;

// Line 67: ia3dSourceEventHandle2 0x004eb400 HANDLE
HANDLE ia3dSourceEventHandle2 ;

// Line 69: iA3DSource_ptr 0x004eb414 IA3dSource*
IA3dSource* iA3DSource_ptr ;

// Line 71: ia3dSourceThreadHandle 0x004eb478 HANDLE
HANDLE ia3dSourceThreadHandle ;

// Line 73: iDirectDrawSurface_ptr3 0x004eb480 LPDIRECTDRAWSURFACE
LPDIRECTDRAWSURFACE iDirectDrawSurface_ptr3 ;

// Line 74: ddSurfaceDesc_3 0x004eb484 _DDSURFACEDESC
_DDSURFACEDESC ddSurfaceDesc_3 ;

// Line 76: Main_settings_menu_only 0x0050b5b0 int
int Main_settings_menu_only ;

// Line 77: Main_settings_debug_hud 0x0050b5c0 int
int Main_settings_debug_hud ;

// Line 79: swrRace_DebugFlag 0x0050c048 char
char swrRace_DebugFlag ;

// Line 81: swrLoader_sprite_file 0x0050c08c FILE*
FILE* swrLoader_sprite_file ;

// Line 82: swrLoader_spline_file 0x0050c090 FILE*
FILE* swrLoader_spline_file ;

// Line 83: swrLoader_texture_file 0x0050c094 FILE*
FILE* swrLoader_texture_file ;

// Line 84: swrLoader_model_file 0x0050c098 FILE*
FILE* swrLoader_model_file ;

// Line 86: swrRace_SelectedRacer 0x0050c118 int
int swrRace_SelectedRacer ;

// Line 88: rdMatrixStack44_size 0x0050c5e8 int
int rdMatrixStack44_size ;

// Line 89: rdMatrixStack34_size 0x0050c6f4 int
int rdMatrixStack34_size ;

// Line 91: swrRace_IsInvincible 0x0050ca28 int
int swrRace_IsInvincible ;

// Line 93: IA3d4_ptr 0x0050d548 IA3d4*
IA3d4* IA3d4_ptr ;

// Line 95: IA3dListener_ptr 0x0050d560 IA3dListener*
IA3dListener* IA3dListener_ptr ;

// Line 97: iDirectInputDeviceA_ptr 0x0050d89c LPDIRECTINPUTDEVICEA
LPDIRECTINPUTDEVICEA iDirectInputDeviceA_ptr ;

// Line 99: iDirectInputA_ptr 0x0050feb8 LPDIRECTINPUTA
LPDIRECTINPUTA iDirectInputA_ptr ;

// Line 101: iDirectPlay4_ptr 0x00510254 IDirectPlay4*
IDirectPlay4* iDirectPlay4_ptr ;

// Line 103: swrConfig_filename 0x005138b8 char[0x80]
char swrConfig_filename[0x80] ;

// Line 104: swrConfig_buffer 0x00528500 char[0x1000]
char swrConfig_buffer[0x1000] ;

// Line 105: swrConfig_file2 0x00529504 FILE*
FILE* swrConfig_file2 ;

// Line 106: swrConfig_file 0x00529508 FILE*
FILE* swrConfig_file ;

// Line 108: iDirectDrawSurface_ptr 0x00529578 LPDIRECTDRAWSURFACE
LPDIRECTDRAWSURFACE iDirectDrawSurface_ptr ;

// Line 109: _ddSurfaceDesc 0x0052957c _DDSURFACEDESC2
_DDSURFACEDESC2 _ddSurfaceDesc ;

// Line 111: iDirectDraw4 0x0052d454 LPDIRECTDRAW
LPDIRECTDRAW iDirectDraw4 ;

// Line 113: d3dDeviceDesc 0x0052d460 D3DDEVICEDESC
D3DDEVICEDESC d3dDeviceDesc ;

// Line 115: iDirectDraw4_2 0x0052e638 LPDIRECTDRAW
LPDIRECTDRAW iDirectDraw4_2 ;

// Line 116: iDirectDrawPalette_ptr 0x0052e63c LPDIRECTDRAWPALETTE
LPDIRECTDRAWPALETTE iDirectDrawPalette_ptr ;

// Line 117: iDirect3D3_ptr 0x0052e640 LPDIRECT3D3
LPDIRECT3D3 iDirect3D3_ptr ;

// Line 118: iDirect3DDevice3_ptr 0x0052e644 LPDIRECT3DDEVICE3
LPDIRECT3DDEVICE3 iDirect3DDevice3_ptr ;

// Line 120: stdFilePrintf_buffer 0x0052e658 char[0x800]
char stdFilePrintf_buffer[0x800] ;

// Line 122: Window_GUID 0x0052ee60 GUID
GUID Window_GUID ;

// Line 123: Window_hWnd 0x0052ee70 HWND
HWND Window_hWnd ;

// Line 124: Window_hinstance 0x0052ee74 HINSTANCE
HINSTANCE Window_hinstance ;

// Line 126: stdConsole_hConsoleOutput 0x0052ee78 HANDLE
HANDLE stdConsole_hConsoleOutput ;

// Line 127: stdConsole_wAttributes 0x0052ee7c WORD
WORD stdConsole_wAttributes ;

// Line 129: rdCamera_camRotation 0x00df7f20 rdVector3
rdVector3 rdCamera_camRotation ;

// Line 130: rdCamera_pCurCamera 0x00df7f2c rdCamera*
rdCamera* rdCamera_pCurCamera ;

// Line 131: bRDroidStartup 0x00df7f30 int
int bRDroidStartup ;

// Line 133: g_hWnd 0x00dfaa28 HWND
HWND g_hWnd ;

// Line 134: g_nCmdShow 0x00dfaa2c int
int g_nCmdShow ;

// Line 135: g_WndProc 0x00dfaa30 Window_MSGHANDLER_ptr
Window_MSGHANDLER_ptr g_WndProc ;

// Line 136: Window_width 0x00dfaa34 int
int Window_width ;

// Line 137: Window_height 0x00dfaa38 int
int Window_height ;

// Line 138: wuRegistry_bInitted 0x00dfaa3c int
int wuRegistry_bInitted ;

// Line 139: wuRegistry_lpSubKey 0x00dfaa40 LPCSTR
LPCSTR wuRegistry_lpSubKey ;

// Line 140: wuRegistry_hKey 0x00dfaa44 HKEY
HKEY wuRegistry_hKey ;

// Line 142: rdMatrix44_unk 0x00dfb21c rdMatrix44
rdMatrix44 rdMatrix44_unk ;

// Line 144: swrRace_deltaTime 0x00e22a40 float
float swrRace_deltaTime ;

// Line 145: swrRace_deltaTime2 0x00e22a50 float
float swrRace_deltaTime2 ;

// Line 147: rdMatrix44_00e25960 0x00e25960 rdMatrix44
rdMatrix44 rdMatrix44_00e25960 ;

// Line 149: swrRace_FireLocation 0x00e25e00 float
float swrRace_FireLocation ;

// Line 151: swrRace_Transition 0x00e295a0 float
float swrRace_Transition ;

// Line 153: swrRace_MenuMaxSelection 0x00e295cc int
int swrRace_MenuMaxSelection ;

// Line 154: swrRace_MenuSelectedItem 0x00e295d0 int
int swrRace_MenuSelectedItem ;

// Line 156: swrRace_lastRaceDamage 0x00e29c40 float
float swrRace_lastRaceDamage ;

// Line 158: swrRace_UnlockDataBase 0x00e35a84 int
int swrRace_UnlockDataBase ;

// Line 160: swrRace_nbPitDroids 0x00e35aa0 int
int swrRace_nbPitDroids ;

// Line 162: rdMatrix44_00e37580 0x00e37580 rdMatrix44
rdMatrix44 rdMatrix44_00e37580 ;

// Line 163: rdMatrixStack34 0x00e375c0 rdMatrix34[0x30]
rdMatrix34 rdMatrixStack34[0x30] ;

// Line 165: rdMatrixStack44 0x00e985c0 rdMatrix44[0x30]
rdMatrix44 rdMatrixStack44[0x30] ;

// Line 167: swrRace_SelectIndex 0x00e99240 int
int swrRace_SelectIndex ;

// Line 169: swrRace_PodRotationAnimation 0x00e99384 float
float swrRace_PodRotationAnimation ;

// Line 171: stdPlatform_hostServices 0x00e9f280 HostServices
HostServices stdPlatform_hostServices ;

// Line 173: rdCamera_mat 0x00ec8580 rdMatrix34
rdMatrix34 rdCamera_mat ;

// Line 174: rdCamera_main_ptr 0x00ec85ec rdCamera*
rdCamera* rdCamera_main_ptr ;

// Line 175: rdCanvas_main_ptr 0x00ec86e0 rdCanvas*
rdCanvas* rdCanvas_main_ptr ;

// Line 177: tagRect 0x00ec86d0 tagRECT
tagRECT tagRect ;

// Line 179: swrRace_ThrottleInput 0x00ec8830 float
float swrRace_ThrottleInput ;

// Line 181: swrRace_PitchInput 0x00ec883c float
float swrRace_PitchInput ;

// Line 183: swrRace_ThrustInput 0x00ec884c float
float swrRace_ThrustInput ;

// Line 185: swrConfig_REFLECTIONS 0x00ec86a0 int
int swrConfig_REFLECTIONS ;

// Line 186: swrConfig_ZEFFECTS 0x00ec86a4 int
int swrConfig_ZEFFECTS ;

// Line 187: swrConfig_DYNAMIC_LIGHTING 0x00ec86a8 int
int swrConfig_DYNAMIC_LIGHTING ;

// Line 188: swrConfig_VSYNC 0x00ec86ac int
int swrConfig_VSYNC ;

// Line 189: swrConfig_LENSFLARE 0x00ec86b0 int
int swrConfig_LENSFLARE ;

// Line 190: swrConfig_ENGINEEXHAUST 0x00ec86b4 int
int swrConfig_ENGINEEXHAUST ;

// Line 191: swrConfig_TEXTURE_RES 0x00ec86b8 int
int swrConfig_TEXTURE_RES ;

// Line 192: swrConfig_MODEL_DETAIL 0x00ec86bc int
int swrConfig_MODEL_DETAIL ;

// Line 193: swrConfig_DRAWDISTANCE 0x00ec86c0 int
int swrConfig_DRAWDISTANCE ;

// Line 195: swrRace_BoostInput 0x00ec8850 float
float swrRace_BoostInput ;

// Line 197: iDirectDrawSurface4_ptr 0x00ec8d00 LPDIRECTDRAWSURFACE4
LPDIRECTDRAWSURFACE4 iDirectDrawSurface4_ptr ;

// Line 198: _ddSurfaceDesc2_2 0x00ec8d04 _DDSURFACEDESC2
_DDSURFACEDESC2 _ddSurfaceDesc2_2 ;

// Line 200: stdVBuffer_main 0x00ec8da0 stdVBuffer
stdVBuffer stdVBuffer_main ;

// Line 205: swrConfig_buffer2 0x00ec9e84 char[0x1000]
char swrConfig_buffer2[0x1000] ;

// Line 207: iDirectInputDeviceA_ptr2 0x00ecb484 LPDIRECTINPUTDEVICEA
LPDIRECTINPUTDEVICEA iDirectInputDeviceA_ptr2 ;

// Line 208: diDevCaps_ptr 0x00ecb488 LPDIDEVCAPS
LPDIDEVCAPS diDevCaps_ptr ;

// Line 210: std_output_buffer 0x00ecbc20 char[0x800]
char std_output_buffer[0x800] ;

// Line 212: stdPlatform_hostServices_ptr 0x00ecc420 HostServices*
HostServices* stdPlatform_hostServices_ptr ;

// Line 213: rdroid_hostServices_ptr 0x00ecc428 HostServices*
HostServices* rdroid_hostServices_ptr ;

// Line 215: rdCamera_camMatrix 0x00ecc440 rdMatrix34
rdMatrix34 rdCamera_camMatrix ;
