#include "globals.h"

#include "types.h"
#include "types_directx.h"

// This file is auto-generated by scripts/GenerateGlobalHeaderFromSymbols.py and data_symbols.syms
// using Jinja template globals.h.j2

// Line 0: diDataFormat 0x0049e720 DIDATAFORMAT
DIDATAFORMAT diDataFormat;

// Line 2: A3dApi_GUID 0x004ae0e8 GUID
GUID A3dApi_GUID;

// Line 3: IID_Ia3d4_GUID 0x004ae128 GUID
GUID IID_Ia3d4_GUID;

// Line 4: IID_IA3dListener_GUID 0x004ae158 GUID
GUID IID_IA3dListener_GUID;

// Line 6: std3D_cfRGB565 0x004ae850 ColorInfo = { STDCOLOR_RGB, 16, 5, 6, 5, 11, 5, 0, 3, 2, 3, 0, 0, 0 }
ColorInfo std3D_cfRGB565 = { STDCOLOR_RGB, 16, 5, 6, 5, 11, 5, 0, 3, 2, 3, 0, 0, 0 };

// Line 7: std3D_cfRGB5551 0x004ae888 ColorInfo = { STDCOLOR_RGBA, 16, 5, 5, 5, 11, 6, 1, 3, 3, 3, 1, 0, 7 }
ColorInfo std3D_cfRGB5551 = { STDCOLOR_RGBA, 16, 5, 5, 5, 11, 6, 1, 3, 3, 3, 1, 0, 7 };

// Line 8: std3D_cfRGB4444 0x004ae8c0 ColorInfo = { STDCOLOR_RGBA, 16, 4, 4, 4, 12, 8, 4, 4, 4, 4, 4, 0, 4 }
ColorInfo std3D_cfRGB4444 = { STDCOLOR_RGBA, 16, 4, 4, 4, 12, 8, 4, 4, 4, 4, 4, 0, 4 };

// Line 10: stdMath_Primes 0x004aeeb0 int[32] = { 0x17, 0x35, 0x4f, 0x65, 0x97, 0xd3, 0xfb, 0x133, 0x161, 0x191, 0x1c9, 0x1f7, 0x22d, 0x259, 0x28d, 0x2bd, 0x2ef, 0x329, 0x355, 0x38b, 0x3b9, 0x3f1, 0x44f, 0x4b1, 0x515, 0x581, 0x5e7, 0x641, 0x6ad, 0x709, 0x76d, 0x7cf }
int stdMath_Primes[32] = { 0x17, 0x35, 0x4f, 0x65, 0x97, 0xd3, 0xfb, 0x133, 0x161, 0x191, 0x1c9, 0x1f7, 0x22d, 0x259, 0x28d, 0x2bd, 0x2ef, 0x329, 0x355, 0x38b, 0x3b9, 0x3f1, 0x44f, 0x4b1, 0x515, 0x581, 0x5e7, 0x641, 0x6ad, 0x709, 0x76d, 0x7cf };

// Line 12: directInputDevice2A_GUID 0x004aefb8 GUID
GUID directInputDevice2A_GUID;

// Line 14: iDirectDraw4_GUID 0x004af1c8 GUID
GUID iDirectDraw4_GUID;

// Line 15: iDirectDrawSurface4_GUID 0x004af208 GUID
GUID iDirectDrawSurface4_GUID;

// Line 16: iDirect3D3_GUID 0x004af278 GUID
GUID iDirect3D3_GUID;

// Line 18: IID_IDirectPlay4_GUID 0x004af4a8 GUID
GUID IID_IDirectPlay4_GUID;

// Line 19: DirectPlay_GUID 0x004af4c8 GUID
GUID DirectPlay_GUID;

// Line 21: Window_UUID 0x004af9b0 uint32_t[4] = { 0xC95FB584, 0x11D2FA31, 0xAA009D90, 0xAD22A300 }
uint32_t Window_UUID[4] = { 0xC95FB584, 0x11D2FA31, 0xAA009D90, 0xAD22A300 };

// Line 23: rdMatrix34_identity 0x004af880 rdMatrix34 = {{1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, {0.0, 0.0, 1.0}, {0.0, 0.0, 0.0}}
rdMatrix34 rdMatrix34_identity = {{1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, {0.0, 0.0, 1.0}, {0.0, 0.0, 0.0}};

// Line 25: swrConfig_joystick_enabled 0x004b2944 int = 1
int swrConfig_joystick_enabled = 1;

// Line 26: swrConfig_keyboard_enabled 0x004b2948 int = 1
int swrConfig_keyboard_enabled = 1;

// Line 27: joystick_detected 0x004b294c int = 1
int joystick_detected = 1;

// Line 29: keyMapping2_0 0x004b29e8 keyMapping2[22]
keyMapping2 keyMapping2_0[22];

// Line 30: keyMapping0 0x004b2af0 keyMapping[7]
keyMapping keyMapping0[7];

// Line 31: keyMapping1 0x004b2b28 keyMapping[21]
keyMapping keyMapping1[21];

// Line 32: keyMapping2 0x004b2bd0 keyMapping[118]
keyMapping keyMapping2[118];

// Line 34: swrConfig_aControlKeyStrings 0x004b38b8 char[17][4] 
char swrConfig_aControlKeyStrings[17][4];

// Line 36: swrSprite_mouseVisible 0x004b4314 int
int swrSprite_mouseVisible;

// Line 38: direct3d_LensFlareCompatible 0x004b431c int
int direct3d_LensFlareCompatible;

// Line 40: swrConfig_defaultVideoConfig 0x004b4330 int[9] = { 0, 0, 0, 0, 0, 0, 1, 3, 2 }
int swrConfig_defaultVideoConfig[9] = { 0, 0, 0, 0, 0, 0, 1, 3, 2 };

// Line 42: iDirectDraw4_error 0x004b4758 int
int iDirectDraw4_error;

// Line 44: zNearEpsilon 0x004b4774 float = 0.001
float zNearEpsilon = 0.001;

// Line 46: Main_force_feedback 0x004b4938 int = 1
int Main_force_feedback = 1;

// Line 48: swrConfig_defaultForceConfig 0x004b4ae8 int[8] = { 3, 3, 2, 2, 2, 2, 1, 1 }
int swrConfig_defaultForceConfig[8] = { 3, 3, 2, 2, 2, 2, 1, 1 };

// Line 50: swrUI_unk_ptr 0x004b5d74 swrUI_unk*
swrUI_unk* swrUI_unk_ptr;

// Line 52: Main_nut_delay_ms 0x004b6718 int = 32
int Main_nut_delay_ms = 32;

// Line 53: Main_hiRes_sound 0x004b6d14 int = 1
int Main_hiRes_sound = 1;

// Line 54: Main_doppler_sound 0x004b6d18 int = 0
int Main_doppler_sound = 0;

// Line 55: Main_sound 0x004b6d20 int = 1
int Main_sound = 1;

// Line 56: Main_sound_gain_adjust 0x004b6d24 float
float Main_sound_gain_adjust;

// Line 57: swrRace_voices_enabled 0x004b6d28 int = 1
int swrRace_voices_enabled = 1;

// Line 58: Main_sound_unk 0x004b6d2c int = 1
int Main_sound_unk = 1;

// Line 60: unknownError_buffer 0x004b75f8 char[1024]
char unknownError_buffer[1024];

// Line 61: Main_fullscreen_unk 0x004b79f8 int = 1
int Main_fullscreen_unk = 1;

// Line 63: Main_display_intro_scene 0x004b7a00 int = 1
int Main_display_intro_scene = 1;

// Line 65: swrMainDisplay_currentDevice 0x004b7a34 int
int swrMainDisplay_currentDevice;

// Line 66: swrMain_GuiAdvanceFunction 0x004b7a38 void*
void* swrMain_GuiAdvanceFunction;

// Line 68: swrSound_criticalSection 0x004b7e7e CRITICAL_SECTION
CRITICAL_SECTION swrSound_criticalSection;

// Line 70: swrSprite_SpriteCount 0x004b91b8 int
int swrSprite_SpriteCount;

// Line 71: swrSprite_unk_x 0x004b91bc float = 16.0
float swrSprite_unk_x = 16.0;

// Line 72: swrSprite_unk_y 0x004b91c0 float = 155.0
float swrSprite_unk_y = 155.0;

// Line 74: eventManagerMain 0x004bfec0 extern swrEventManager[][9]; 
extern swrEventManager eventManagerMain[][9];;

// Line 75: swrObjHang_unused_state 0x004bfec8 swrObjHang_STATE = -1
swrObjHang_STATE swrObjHang_unused_state = -1;

// Line 76: swrObjHang_unused_unk 0x004bfecc int = -1
int swrObjHang_unused_unk = -1;

// Line 78: swrObjHang_state2 0x004bfedc swrObjHang_STATE = -1
swrObjHang_STATE swrObjHang_state2 = -1;

// Line 80: time_ms_unk 0x004c00a8 float;
float; time_ms_unk;

// Line 82: rdVector_negZ 0x004c2598 rdVector3 = {0.0, 0.0, -1.0}
rdVector3 rdVector_negZ = {0.0, 0.0, -1.0};

// Line 84: ai_antiskid 0x004c3114 float
float ai_antiskid;

// Line 85: ai_turn_response 0x004c3118 float
float ai_turn_response;

// Line 86: ai_max_turn_rate 0x004c311c float
float ai_max_turn_rate;

// Line 87: ai_acceleration 0x004c3120 float
float ai_acceleration;

// Line 88: ai_max_speed 0x004c3124 float
float ai_max_speed;

// Line 89: ai_air_brake_interval 0x004c3128 float
float ai_air_brake_interval;

// Line 90: ai_deceleration_interval 0x004c312c float
float ai_deceleration_interval;

// Line 91: ai_boost_thrust 0x004c3130 float
float ai_boost_thrust;

// Line 92: ai_heat_rate 0x004c3134 float
float ai_heat_rate;

// Line 93: ai_cool_rate 0x004c3138 float
float ai_cool_rate;

// Line 94: ai_hover_height 0x004c313c float
float ai_hover_height;

// Line 95: ai_repair_rate 0x004c3140 float
float ai_repair_rate;

// Line 96: ai_bump_mass 0x004c3144 float
float ai_bump_mass;

// Line 97: ai_damage_immunity 0x004c3148 float
float ai_damage_immunity;

// Line 98: ai_intersect_radius 0x004c314c float
float ai_intersect_radius;

// Line 101: rdMatrixStack34_modified 0x004c3c0c int
int rdMatrixStack34_modified;

// Line 103: rdMatrix_unk5 0x004c3c38 rdMatrix44 = {{-1.0 / 6.0, 0.5, -0.5, 1.0 / 6.0}, {0.5, -1.0, 0.5, 0.0}, {-0.5, 0.0, 0.5, 0.0}, {1.0 /6.0, 2.0 / 3.0, 1.0 / 6.0, 0.0}}
rdMatrix44 rdMatrix_unk5 = {{-1.0 / 6.0, 0.5, -0.5, 1.0 / 6.0}, {0.5, -1.0, 0.5, 0.0}, {-0.5, 0.0, 0.5, 0.0}, {1.0 /6.0, 2.0 / 3.0, 1.0 / 6.0, 0.0}};

// Line 104: rdMatrix_unk3 0x004c3c78 rdMatrix44 = {{0.0, 0.0, 0.0, 0.0}, {-0.5, 1.5, -1.5, 0.5}, {1.0, -2.0, 1.0, 0.0}, {-0.5, 0.0, 0.5, 0.0}}
rdMatrix44 rdMatrix_unk3 = {{0.0, 0.0, 0.0, 0.0}, {-0.5, 1.5, -1.5, 0.5}, {1.0, -2.0, 1.0, 0.0}, {-0.5, 0.0, 0.5, 0.0}};

// Line 105: rdMatrix_unk1 0x004c3cb8 rdMatrix44 = {{0.0, 0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}, {-1.0, 3.0, -3.0, 1.0}, {1.0, -2.0, 1.0, 0.0}}
rdMatrix44 rdMatrix_unk1 = {{0.0, 0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}, {-1.0, 3.0, -3.0, 1.0}, {1.0, -2.0, 1.0, 0.0}};

// Line 106: rdMatrix_unk6 0x004c3cf8 rdMatrix44 = {{-1.0, 3.0, -3.0, 1.0}, {3.0, -6.0, 3.0, 0.0}, {-3.0, 3.0, 0.0, 0.0}, {1.0, 0.0, 0.0, 0.0}}
rdMatrix44 rdMatrix_unk6 = {{-1.0, 3.0, -3.0, 1.0}, {3.0, -6.0, 3.0, 0.0}, {-3.0, 3.0, 0.0, 0.0}, {1.0, 0.0, 0.0, 0.0}};

// Line 107: rdMatrix_unk4 0x004c3d38 rdMatrix44 = {{0.0, 0.0, 0.0, 0.0}, {-3.0, 9.0, -9.0, 3.0}, {6.0, -12.0, 6.0, 0.0}, {-3.0, 3.0, 0.0, 0.0}}
rdMatrix44 rdMatrix_unk4 = {{0.0, 0.0, 0.0, 0.0}, {-3.0, 9.0, -9.0, 3.0}, {6.0, -12.0, 6.0, 0.0}, {-3.0, 3.0, 0.0, 0.0}};

// Line 108: rdMatrix_unk2 0x004c3d78 rdMatrix44 = {{0.0, 0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}, {-6.0, 18.0, -18.0, 6.0}, {6.0, -12.0, 6.0, 0.0}}
rdMatrix44 rdMatrix_unk2 = {{0.0, 0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}, {-6.0, 18.0, -18.0, 6.0}, {6.0, -12.0, 6.0, 0.0}};

// Line 110: ai_level 0x004c707c float
float ai_level;

// Line 111: ai_spread 0x004c7080 float
float ai_spread;

// Line 113: Main_sound_3dimpact 0x004c7aa8 int = -1
int Main_sound_3dimpact = -1;

// Line 115: death_speedMin 0x004c7bb8 float
float death_speedMin;

// Line 116: death_speedDrop 0x004c7bbc float
float death_speedDrop;

// Line 118: Main_sound_gain_const 0x004c7d70 float = 0.8
float Main_sound_gain_const = 0.8;

// Line 119: Main_sound_doppler_scale 0x004c7d74 float = 1.0
float Main_sound_doppler_scale = 1.0;

// Line 120: Main_sound_rolloff 0x004c7d78 float = 0.15
float Main_sound_rolloff = 0.15;

// Line 121: Main_sound_gain 0x004c7d7c float = 1.0
float Main_sound_gain = 1.0;

// Line 122: Sound_A3Dinitted 0x004c7d80 int = 1
int Sound_A3Dinitted = 1;

// Line 124: swrRace_AILevel 0x004c707c int
int swrRace_AILevel;

// Line 126: swrRace_DeathSpeedMin 0x004c7bb8 float = 325.00
float swrRace_DeathSpeedMin = 325.00;

// Line 127: swrRace_DeathSpeedDrop 0x004c7bbc float = 140.0
float swrRace_DeathSpeedDrop = 140.0;

// Line 129: swrRace_FireTimer 0x004c7bc0 float = -1.0
float swrRace_FireTimer = -1.0;

// Line 131: sithControl_secFPS 0x004c8174 float
float sithControl_secFPS;

// Line 132: sithControl_msecFPS 0x004c8178 float
float sithControl_msecFPS;

// Line 134: stdDisplay_FillMainSurface_ptr 0x004c86b8 void*
void* stdDisplay_FillMainSurface_ptr;

// Line 135: stdDisplay_coopLevelFlags 0x004c86bc int
int stdDisplay_coopLevelFlags;

// Line 136: directDraw_BltFillColor 0x004c86c0 int
int directDraw_BltFillColor;

// Line 138: d3d_FogEnabled 0x004c98b0 int = 1
int d3d_FogEnabled = 1;

// Line 139: std3D_frameCount 0x004c98b4 int = 1 
int std3D_frameCount = 1 ;

// Line 141: stdMath_SinTable 0x004c98e8 float[4096]
float stdMath_SinTable[4096];

// Line 142: stdMath_TanTable 0x004cd8e8 float[4096]
float stdMath_TanTable[4096];

// Line 144: wuRegistry_lpClass 0x004d55cc LPSTR
LPSTR wuRegistry_lpClass;

// Line 146: multiplayer_enabled 0x004d5e00 int
int multiplayer_enabled;

// Line 148: sithMessage_g_localPlayerId 0x004d5e08 int
int sithMessage_g_localPlayerId;

// Line 149: sithMessage_totalSentDataSize 0x004d5e0c int
int sithMessage_totalSentDataSize;

// Line 150: sithMessage_totalNetSent 0x004d5e10 int
int sithMessage_totalNetSent;

// Line 152: swrText_keyNameText 0x004d5f38 char[128]
char swrText_keyNameText[128];

// Line 154: WindowsInputStack 0x004d6310 WindowsInputItem[64]
WindowsInputItem WindowsInputStack[64];

// Line 156: swrConfig_mouse_enabled 0x004d6b38 int
int swrConfig_mouse_enabled;

// Line 157: stdControl_joystickDeviceIndex 0x004d6b3c int
int stdControl_joystickDeviceIndex;

// Line 159: rdLight_1 0x004d6b78 rdLight
rdLight rdLight_1;

// Line 160: rdLight_2 0x004d6ba8 rdLight
rdLight rdLight_2;

// Line 162: directDrawSurface4_ptr2 0x004d6be0 LPDIRECTDRAWSURFACE4
LPDIRECTDRAWSURFACE4 directDrawSurface4_ptr2;

// Line 163: ddSurfaceDesc_2 0x004d6be4 DDSURFACEDESC
DDSURFACEDESC ddSurfaceDesc_2;

// Line 165: defaultMaterial 0x004d6c60 RdMaterial
RdMaterial defaultMaterial;

// Line 167: swrModel3_root_materials 0x004d6c68 RdMaterial**
RdMaterial** swrModel3_root_materials;

// Line 168: swrModel3_root_numMaterials 0x004d6c6c int
int swrModel3_root_numMaterials;

// Line 170: stdDisplay_ScreenshotIndex 0x004d79e4 int
int stdDisplay_ScreenshotIndex;

// Line 172: swrSpriteTexIsTGA 0x004d79f8 int[149]
int swrSpriteTexIsTGA[149];

// Line 174: swrSpriteTexItems 0x004d7c68 swrSpriteTexItem[149]
swrSpriteTexItem swrSpriteTexItems[149];

// Line 176: swrUI_unk4_ptr 0x004d878c swrUI_unk*
swrUI_unk* swrUI_unk4_ptr;

// Line 177: swrUI_unk5_ptr 0x004d8790 swrUI_unk*
swrUI_unk* swrUI_unk5_ptr;

// Line 178: swrUI_unk6_ptr 0x004d8794 swrUI_unk*
swrUI_unk* swrUI_unk6_ptr;

// Line 180: multiplayer_in_mp 0x004d87a0 int
int multiplayer_in_mp;

// Line 182: swrUI_unk_array 0x004d8110 swrUI_unk*[20]
swrUI_unk* swrUI_unk_array[20];

// Line 184: swrUI_unk_array_count 0x004d87a4 int
int swrUI_unk_array_count;

// Line 186: swr_unk_array2 0x004e9918 int[256]
int swr_unk_array2[256];

// Line 187: swrHook_multiplayer 0x004e9d18 void*[100]
void* swrHook_multiplayer[100];

// Line 189: sithMessage_g_outputstream 0x004e9eac unsigned int
unsigned int sithMessage_g_outputstream;

// Line 190: sithMessage_g_inputstream 0x004e9eb0 unsigned int
unsigned int sithMessage_g_inputstream;

// Line 192: time_buffer 0x004e9f20 char[256]
char time_buffer[256];

// Line 194: g_objHang1 0x004eb21c swrObjHang*
swrObjHang* g_objHang1;

// Line 196: multiplayer_sync_timer_ms 0x004eb230 int
int multiplayer_sync_timer_ms;

// Line 198: multiplayer_race_button_toggle 0x004eb238 int
int multiplayer_race_button_toggle;

// Line 200: multiplayer_track_change_permission 0x004eb388 int
int multiplayer_track_change_permission;

// Line 202: stdComm_bInitted 0x004eb394 int
int stdComm_bInitted;

// Line 204: playerNumber 0x004eb3b4 int
int playerNumber;

// Line 205: sithPlayer_g_numPlayers 0x004eb38 int 
int sithPlayer_g_numPlayers;

// Line 207: swrText_racerTab_array 0x004eb3c4 char**
char** swrText_racerTab_array;

// Line 208: swrText_racerTab_buffer 0x004eb3c8 char*
char* swrText_racerTab_buffer;

// Line 210: swrText_nbLinesRacerTab 0x004eb3cc int
int swrText_nbLinesRacerTab;

// Line 212: ia3dSourceThreadId 0x004eb3f8 DWORD
DWORD ia3dSourceThreadId;

// Line 213: ia3dSourceEventHandle 0x004eb3fc HANDLE
HANDLE ia3dSourceEventHandle;

// Line 214: ia3dSourceEventHandle2 0x004eb400 HANDLE
HANDLE ia3dSourceEventHandle2;

// Line 216: iA3DSource_ptr 0x004eb414 IA3dSource*
IA3dSource* iA3DSource_ptr;

// Line 218: swrSound_Initted 0x004eb450 int
int swrSound_Initted;

// Line 220: swrSound_Ready 0x004eb458 int
int swrSound_Ready;

// Line 221: swrRace_music_enabled 0x004eb45c int
int swrRace_music_enabled;

// Line 223: swrSoundHashTable 0x004eb464 tHashTable*
tHashTable* swrSoundHashTable;

// Line 225: swrSound_Playing 0x004eb474 int
int swrSound_Playing;

// Line 226: ia3dSourceThreadHandle 0x004eb478 HANDLE
HANDLE ia3dSourceThreadHandle;

// Line 227: ia3d_thread_running 0x004eb47c int
int ia3d_thread_running;

// Line 229: iDirectDrawSurface_ptr3 0x004eb480 LPDIRECTDRAWSURFACE
LPDIRECTDRAWSURFACE iDirectDrawSurface_ptr3;

// Line 230: ddSurfaceDesc_3 0x004eb484 DDSURFACEDESC
DDSURFACEDESC ddSurfaceDesc_3;

// Line 232: swrMainDisplayWindow 0x004eb500 swrDisplayWindow
swrDisplayWindow swrMainDisplayWindow;

// Line 234: Windows_windowWidth 0x004eb550 int
int Windows_windowWidth;

// Line 236: Windows_windowHeight 0x0050b594 int
int Windows_windowHeight;

// Line 237: Windows_hinstance_unused 0x0050b598 int
int Windows_hinstance_unused;

// Line 239: swrMain_initialized 0x0050b5a0 int
int swrMain_initialized;

// Line 241: Windows_WinProc_res 0x0050b5a8 LRESULT
LRESULT Windows_WinProc_res;

// Line 243: swrMainDisplay_windowed 0x0050b5c8 int
int swrMainDisplay_windowed;

// Line 245: swrMainDisplaySettings_g 0x0050b560 swrMainDisplaySettings
swrMainDisplaySettings swrMainDisplaySettings_g;

// Line 247: Main_hWnd 0x0050b59c HWND 
HWND Main_hWnd;

// Line 249: swrScene_animations_count 0x0050b5ec int
int swrScene_animations_count;

// Line 251: rdVector_sound_pos 0x0050b5f0 rdVector4
rdVector4 rdVector_sound_pos;

// Line 254: Main_drawDevices 0x0050b5ac swrDrawDevices*
swrDrawDevices* Main_drawDevices;

// Line 255: Main_settings_menu_only 0x0050b5b0 int
int Main_settings_menu_only;

// Line 256: Main_settings_debug_hud 0x0050b5c0 int
int Main_settings_debug_hud;

// Line 258: Window_Active 0x0050b5d0 int
int Window_Active;

// Line 260: swrSprite_unk1_r 0x0050b704 char
char swrSprite_unk1_r;

// Line 261: swrSprite_unk1_g 0x0050b705 char
char swrSprite_unk1_g;

// Line 262: swrSprite_unk1_b 0x0050b706 char
char swrSprite_unk1_b;

// Line 263: swrSprite_unk1_a 0x0050b707 char
char swrSprite_unk1_a;

// Line 264: swrSprite_unk2_r 0x0050b708 char
char swrSprite_unk2_r;

// Line 265: swrSprite_unk2_g 0x0050b709 char
char swrSprite_unk2_g;

// Line 266: swrSprite_unk2_b 0x0050b70a char
char swrSprite_unk2_b;

// Line 267: swrSprite_unk2_a 0x0050b70b char
char swrSprite_unk2_a;

// Line 269: swrRace_DebugLevel 0x0050c040 int
int swrRace_DebugLevel;

// Line 270: swrRace_DebugMenu 0x0050c044 int 
int swrRace_DebugMenu;

// Line 271: swrRace_DebugFlag 0x0050c048 char 
char swrRace_DebugFlag;

// Line 273: swrLoader_sprite_file 0x0050c08c FILE*
FILE* swrLoader_sprite_file;

// Line 274: swrLoader_spline_file 0x0050c090 FILE*
FILE* swrLoader_spline_file;

// Line 275: swrLoader_texture_file 0x0050c094 FILE*
FILE* swrLoader_texture_file;

// Line 276: swrLoader_model_file 0x0050c098 FILE*
FILE* swrLoader_model_file;

// Line 278: DebugMenuState 0x0050c07c int
int DebugMenuState;

// Line 280: swrRace_SelectedRacer 0x0050c118 int
int swrRace_SelectedRacer;

// Line 282: alpha_unk 0x0050c2e8 float
float alpha_unk;

// Line 283: gamma_unk 0x0050c2ec float
float gamma_unk;

// Line 285: g_objHang2 0x0050c454 swrObjHang*
swrObjHang* g_objHang2;

// Line 287: rdroid_g_curRenderOptions2 0x0050c530 RdroidFlags
RdroidFlags rdroid_g_curRenderOptions2;

// Line 289: swrRace_TournamentTrugutGain 0x0050c53c int
int swrRace_TournamentTrugutGain;

// Line 291: nb_AI_racers 0x0050c558 int
int nb_AI_racers;

// Line 293: rdMatrixStack44_size 0x0050c5e8 int
int rdMatrixStack44_size;

// Line 295: assetBufferIndex 0x0050c614 int
int assetBufferIndex;

// Line 297: swrSound_Orientation1 0x0050c648 rdVector4
rdVector4 swrSound_Orientation1;

// Line 298: swrSound_Orientation2 0x0050c658 rdVector4
rdVector4 swrSound_Orientation2;

// Line 299: swrSound_Position 0x0050c668 rdVector4
rdVector4 swrSound_Position;

// Line 301: swrSound_unk_init 0x0050c68c int
int swrSound_unk_init;

// Line 302: swrSound_Velocity 0x0050c690 rdVector3
rdVector3 swrSound_Velocity;

// Line 304: IA3dSource2_ptr 0x0050c6a0 IA3dSource*
IA3dSource* IA3dSource2_ptr;

// Line 305: IA3dSource3_ptr 0x0050c6a4 IA3dSource*
IA3dSource* IA3dSource3_ptr;

// Line 307: swr_rootModel_ptr 0x0050c6b0 RdModel3*
RdModel3* swr_rootModel_ptr;

// Line 308: rdMatrix44_ringBufferIndex 0x0050c6b8 int
int rdMatrix44_ringBufferIndex;

// Line 309: swr_rootThing_ptr 0x0050c6bc swrUI_Unk3*
swrUI_Unk3* swr_rootThing_ptr;

// Line 311: rdVector_model_translation 0x0050c6e8 rdVector3
rdVector3 rdVector_model_translation;

// Line 313: swrTextEntries1Count 0x0050c750 int 
int swrTextEntries1Count;

// Line 315: swrTextEntries2Count 0x0050c758 int 
int swrTextEntries2Count;

// Line 317: rdMatrixStack34_size 0x0050c6f4 int
int rdMatrixStack34_size;

// Line 319: debug_showSurfaceFlags 0x0050c88c int
int debug_showSurfaceFlags;

// Line 321: debug_showSplineMarkers 0x0050ca24 int
int debug_showSplineMarkers;

// Line 322: swrRace_IsInvincible 0x0050ca28 int
int swrRace_IsInvincible;

// Line 324: swr_systemTimeMs 0x0050cb60 DWORD
DWORD swr_systemTimeMs;

// Line 325: swrGui_Stopped 0x0050cb64 int
int swrGui_Stopped;

// Line 327: swr_FastMode 0x0050cb68 int
int swr_FastMode;

// Line 329: cman_unk_mat44 0x0050cb88 rdMatrix44
rdMatrix44 cman_unk_mat44;

// Line 331: unk_counter 0x0050cd10 int
int unk_counter;

// Line 333: debug_buffer 0x0050cd18 char[2048]
char debug_buffer[2048];

// Line 335: stdPlatform_hostServices_initialized 0x0050d518 int
int stdPlatform_hostServices_initialized;

// Line 337: a3dCaps_hardware 0x0050d520 A3DCAPS_HARDWARE
A3DCAPS_HARDWARE a3dCaps_hardware;

// Line 338: a3dOutputGain 0x0050d544 float
float a3dOutputGain;

// Line 339: IA3d4_ptr 0x0050d548 IA3d4*
IA3d4* IA3d4_ptr;

// Line 341: Sound_enabled_3d 0x0050d550 int
int Sound_enabled_3d;

// Line 342: Sound_FirstReflexionsSupport 0x0050d554 int
int Sound_FirstReflexionsSupport;

// Line 343: Sound_HardwareDetected 0x0050d55c int
int Sound_HardwareDetected;

// Line 345: IA3dListener_ptr 0x0050d560 IA3dListener*
IA3dListener* IA3dListener_ptr;

// Line 347: stdControl_aAxisPos 0x0050d568 int[15]
int stdControl_aAxisPos[15];

// Line 349: DirectInputKeyboards 0x0050d658 void*
void* DirectInputKeyboards;

// Line 351: stdControlKeyboardDevice 0x0050d89c LPDIRECTINPUTDEVICEA
LPDIRECTINPUTDEVICEA stdControlKeyboardDevice;

// Line 352: stdControl_aKeyIdleTimes 0x0050e028 int[528]
int stdControl_aKeyIdleTimes[528];

// Line 353: stdControl_aKeyInfos 0x0050e868 int[528]
int stdControl_aKeyInfos[528];

// Line 355: stdControl_aAxes 0x0050f0a8 StdControlAxis[60]
StdControlAxis stdControl_aAxes[60];

// Line 357: stdControl_g_aKeyPressCounter 0x0050f668 int[528]
int stdControl_g_aKeyPressCounter[528];

// Line 358: stdControl_g_bStartup 0x0050fea8 int
int stdControl_g_bStartup;

// Line 359: stdControl_g_bOpen 0x0050feac int
int stdControl_g_bOpen;

// Line 361: stdControl_bControlsIdle 0x0050feb0 int
int stdControl_bControlsIdle;

// Line 362: stdControl_bControlsActive 0x0050feb4 int
int stdControl_bControlsActive;

// Line 363: iDirectInputA_ptr 0x0050feb8 LPDIRECTINPUTA
LPDIRECTINPUTA iDirectInputA_ptr;

// Line 364: DirectInputNbKeyboard 0x00febc int 
int DirectInputNbKeyboard;

// Line 366: DirectInputNbMouses 0x0050fec0 int 
int DirectInputNbMouses;

// Line 367: stdControl_bReadJoysticks 0x0050fec4 int
int stdControl_bReadJoysticks;

// Line 369: stdControl_numJoystickDevices 0x0050fec8 int 
int stdControl_numJoystickDevices;

// Line 370: stdControl_curReadTime 0x0050fecc int
int stdControl_curReadTime;

// Line 371: stdControl_lastReadTime 0x0050fed0 int
int stdControl_lastReadTime;

// Line 373: stdControl_readDeltaTime 0x0050fed8 int
int stdControl_readDeltaTime;

// Line 375: stdComm_aPlayerInfos 0x0050fee0 StdCommPlayerInfo[20]
StdCommPlayerInfo stdComm_aPlayerInfos[20];

// Line 377: stdComm_numPlayers 0x00510250 int
int stdComm_numPlayers;

// Line 378: stdComm_pDirectPlay 0x00510254 IDirectPlay4*
IDirectPlay4* stdComm_pDirectPlay;

// Line 379: stdComm_bIsServer 0x00510258 int
int stdComm_bIsServer;

// Line 381: stdComm_Connections 0x00510260 StdCommConnection[16]
StdCommConnection stdComm_Connections[16];

// Line 383: stdCommSessionSettings 0x005117e8 StdCommSessionSettings[32]
StdCommSessionSettings stdCommSessionSettings[32];

// Line 385: stdComm_bGameActive 0x0051386c int
int stdComm_bGameActive;

// Line 387: stdComm_numConnections 0x00513868 int
int stdComm_numConnections;

// Line 389: stdComm_numSessionSettings 0x00513870 int
int stdComm_numSessionSettings;

// Line 391: stdConffile_aWriteFilename 0x005138b8 char[0x80]
char stdConffile_aWriteFilename[0x80];

// Line 392: stdConffile_aFilenameStack 0x00513938 char[20][128]
char stdConffile_aFilenameStack[20][128];

// Line 393: stdConffile_apBufferStack 0x00514338 char*[20]
char* stdConffile_apBufferStack[20];

// Line 394: stdConffile_linenumStack 0x00514388 int[20]
int stdConffile_linenumStack[20];

// Line 395: stdConffile_pFilename 0x005143d8 char[0x80]
char stdConffile_pFilename[0x80];

// Line 396: stdConffile_aEntryStack 0x00514458 StdConffileEntry[20]
StdConffileEntry stdConffile_aEntryStack[20];

// Line 397: stdConffile_openFileStack 0x005284a8 FILE*[20]
FILE* stdConffile_openFileStack[20];

// Line 398: stdConffile_linenum 0x005284f8 int
int stdConffile_linenum;

// Line 399: swrConfig_buffer 0x00528500 char[0x1000]
char swrConfig_buffer[0x1000];

// Line 400: stdConffile_bOpen 0x00529500 int
int stdConffile_bOpen;

// Line 401: stdConffile_openFile 0x00529504 FILE*
FILE* stdConffile_openFile;

// Line 402: stdConffile_writeFile 0x00529508 FILE*
FILE* stdConffile_writeFile;

// Line 403: stdConffile_stackLevel 0x0052950c int
int stdConffile_stackLevel;

// Line 404: stdDisplay_hFont 0x00529510 HFONT
HFONT stdDisplay_hFont;

// Line 405: stdDisplay_curDevice 0x00529514 int
int stdDisplay_curDevice;

// Line 406: stdDisplay_primaryVideoMode 0x00529518 StdVideoMode
StdVideoMode stdDisplay_primaryVideoMode;

// Line 408: stdDisplay_backbufHeight 0x00529570 int
int stdDisplay_backbufHeight;

// Line 409: stdDisplay_backbufWidth 0x00529574 int
int stdDisplay_backbufWidth;

// Line 411: stdDisplay_zBuffer 0x00529578 tVSurface
tVSurface stdDisplay_zBuffer;

// Line 412: _ddSurfaceDesc 0x0052957c DDSURFACEDESC2
DDSURFACEDESC2 _ddSurfaceDesc;

// Line 413: stdDisplay_aVideoModes 0x005295f8 swrDisplayMode[32]
swrDisplayMode stdDisplay_aVideoModes[32];

// Line 415: stdDisplay_aDisplayDevices 0x0052a9f8 swrDrawDevice[16]
swrDrawDevice stdDisplay_aDisplayDevices[16];

// Line 417: stdDisplay_bStartup 0x0052d438 int
int stdDisplay_bStartup;

// Line 418: stdDisplay_bOpen 0x0052d43c int
int stdDisplay_bOpen;

// Line 420: stdDisplay_bModeSet 0x0052d440 int
int stdDisplay_bModeSet;

// Line 421: stdDisplay_numDevices 0x0052d444 int
int stdDisplay_numDevices;

// Line 422: stdDisplay_pcurDevice 0x0052d448 swrDrawDevice*
swrDrawDevice* stdDisplay_pcurDevice;

// Line 423: stdDisplay_numVideoModes 0x0052d44c int
int stdDisplay_numVideoModes;

// Line 424: stdDisplay_pCurVideMode 0x0052d450 swrDisplayMode*
swrDisplayMode* stdDisplay_pCurVideMode;

// Line 425: stdDisplay_lpDD 0x0052d454 LPDIRECTDRAW
LPDIRECTDRAW stdDisplay_lpDD;

// Line 426: stdDisplay_bFullscreen 0x0052d458 int
int stdDisplay_bFullscreen;

// Line 428: directDrawSpecialDeviceId 0x0052d45c int
int directDrawSpecialDeviceId;

// Line 430: d3dDeviceDesc 0x0052d460 D3DDEVICEDESC
D3DDEVICEDESC d3dDeviceDesc;

// Line 432: std3D_curDevice 0x0052d55c int
int std3D_curDevice;

// Line 433: std3D_RGBA_TextureFormat 0x0052d560 int
int std3D_RGBA_TextureFormat;

// Line 434: std3D_RGBTextureFormat 0x0052d564 int
int std3D_RGBTextureFormat;

// Line 435: std3D_RGBAKeyTextureFormat 0x0052d568 int
int std3D_RGBAKeyTextureFormat;

// Line 436: std3D_numDevices 0x0052d56c int
int std3D_numDevices;

// Line 437: std3D_aTextureFormats 0x0052d570 stdTextureFormat[8]
stdTextureFormat std3D_aTextureFormats[8];

// Line 439: std3D_aDevices 0x0052d870 swr3DDevice[4]
swr3DDevice std3D_aDevices[4];

// Line 440: std3D_renderState 0x0052e610 unsigned int
unsigned int std3D_renderState;

// Line 441: d3dMipFilter 0x0052e614 unsigned int
unsigned int d3dMipFilter;

// Line 442: std3D_pCurDevice 0x0052e618 Device3D*
Device3D* std3D_pCurDevice;

// Line 443: std3D_numTextureFormats 0x0052e61c int
int std3D_numTextureFormats;

// Line 444: std3D_bHasRGBTextureFormat 0x0052e620 int
int std3D_bHasRGBTextureFormat;

// Line 445: std3D_g_maxVertices 0x0052d624 unsigned int
unsigned int std3D_g_maxVertices;

// Line 446: std3D_pD3DTex 0x0052e628 IDirect3DTexture2*
IDirect3DTexture2* std3D_pD3DTex;

// Line 447: std3D_numCachedTextures 0x0052e62c int
int std3D_numCachedTextures;

// Line 448: std3D_pFirstTexCache 0x0052e630 int
int std3D_pFirstTexCache;

// Line 449: std3D_pLastTexCache 0x0052e634 int
int std3D_pLastTexCache;

// Line 450: std3D_aDevices 0x0052e638 LPDIRECTDRAW
LPDIRECTDRAW std3D_aDevices;

// Line 451: std3D_pDDPalette 0x0052e63c LPDIRECTDRAWPALETTE
LPDIRECTDRAWPALETTE std3D_pDDPalette;

// Line 452: std3D_pDirect3D 0x0052e640 LPDIRECT3D3
LPDIRECT3D3 std3D_pDirect3D;

// Line 453: std3D_pD3Device 0x0052e644 LPDIRECT3DDEVICE3
LPDIRECT3DDEVICE3 std3D_pD3Device;

// Line 454: std3D_lpD3DViewPort 0x0052e648 IDirect3DViewport3*
IDirect3DViewport3* std3D_lpD3DViewPort;

// Line 455: std3D_bStartup 0x0052e64c int 
int std3D_bStartup;

// Line 456: std3D_bOpen 0x0052e650 int
int std3D_bOpen;

// Line 458: stdFilePrintf_buffer 0x0052e658 char[0x800]
char stdFilePrintf_buffer[0x800];

// Line 460: Window_GUID 0x0052ee60 GUID
GUID Window_GUID;

// Line 461: Window_hWnd 0x0052ee70 HWND
HWND Window_hWnd;

// Line 462: Window_hinstance 0x0052ee74 HINSTANCE
HINSTANCE Window_hinstance;

// Line 464: stdConsole_hConsoleOutput 0x0052ee78 HANDLE
HANDLE stdConsole_hConsoleOutput;

// Line 465: stdConsole_wAttributes 0x0052ee7c WORD
WORD stdConsole_wAttributes;

// Line 467: daAlloc_struct 0x0052ee98 void*
void* daAlloc_struct;

// Line 469: rdCache_aProcFaces 0x005330c0 RdCacheProcEntry[1] 
RdCacheProcEntry rdCache_aProcFaces[1];

// Line 471: rdCache_aVertIntensities 0x005430c8 rdVector4[1] 
rdVector4 rdCache_aVertIntensities[1];

// Line 473: rdCache_aAlphaProcFaces 0x006830c8 RdCacheProcEntry[1] 
RdCacheProcEntry rdCache_aAlphaProcFaces[1];

// Line 475: rdCache_numProcFaces 0x006930c8 int
int rdCache_numProcFaces;

// Line 477: rdCache_numAlphaProcFaces 0x00af30d8 int 
int rdCache_numAlphaProcFaces;

// Line 479: rdCache_aVertIndices 0x00af30e8 WORD[2] 
WORD rdCache_aVertIndices[2];

// Line 481: rdCache_aHWVertices 0x00b6b0e8 D3DTLVERTEX[1] 
D3DTLVERTEX rdCache_aHWVertices[1];

// Line 483: rdCache_drawnFaces 0x00deb0e8 int
int rdCache_drawnFaces;

// Line 484: rdCache_frameNum 0x00deb0ec int
int rdCache_frameNum;

// Line 485: rdCache_numUsedVertices 0x00deb0f0 int
int rdCache_numUsedVertices;

// Line 486: rdCache_numUsedTexVertices 0x00deb0f4 int
int rdCache_numUsedTexVertices;

// Line 487: rdCache_numUsedIntensities 0x00deb0f8 int
int rdCache_numUsedIntensities;

// Line 489: rdMaterial_pMaterialsLoader 0x00deb108 void*
void* rdMaterial_pMaterialsLoader;

// Line 490: rdMaterial_pMaterialUnloader 0x00deb10c void*
void* rdMaterial_pMaterialUnloader;

// Line 491: rdModel3_pCurGeoSet 0x00deb110 rdModel3GeoSet*
rdModel3GeoSet* rdModel3_pCurGeoSet;

// Line 493: rdModel3_g_localCamera 0x00deb118 rdVector3
rdVector3 rdModel3_g_localCamera;

// Line 495: rdModel3_g_apGeoLights 0x00deb4e8 RdLight*[1] 
RdLight* rdModel3_g_apGeoLights[1];

// Line 497: rdModel3_g_aLocalLightPos 0x00deb6e8 rdVector3[1] 
rdVector3 rdModel3_g_aLocalLightPos[1];

// Line 499: rdModel3_aView 0x00debce8 rdVector3[1] 
rdVector3 rdModel3_aView[1];

// Line 501: rdModel3_g_pCurMesh 0x00df7ce8 rdModel3Mesh*
rdModel3Mesh* rdModel3_g_pCurMesh;

// Line 502: rdModel3_pCurModel 0x00df7cec RdModel3*
RdModel3* rdModel3_pCurModel;

// Line 504: rdroid_g_curLightingMode2 0x00df7cf0 RdLightMode
RdLightMode rdroid_g_curLightingMode2;

// Line 506: rdModel3_apMeshLights 0x00df7cf8 RdLight*[1] 
RdLight* rdModel3_apMeshLights[1];

// Line 508: rdModel3_pCurThing 0x00df7ef8 RdThing*
RdThing* rdModel3_pCurThing;

// Line 509: rdModel3_g_lightingMode 0x00df7efc RdLightMode
RdLightMode rdModel3_g_lightingMode;

// Line 511: rdModel3_g_numGeoLights 0x00df7f08 int
int rdModel3_g_numGeoLights;

// Line 512: rdModel3_g_numMeshLights 0x00df7f0c int
int rdModel3_g_numMeshLights;

// Line 514: rdCamera_camRotation 0x00df7f20 rdVector3
rdVector3 rdCamera_camRotation;

// Line 515: rdCamera_pCurCamera 0x00df7f2c rdCamera*
rdCamera* rdCamera_pCurCamera;

// Line 516: bRDroidStartup 0x00df7f30 int
int bRDroidStartup;

// Line 517: rdroid_bRDroidOpen 0x00df7f34 int
int rdroid_bRDroidOpen;

// Line 519: rdFont_bStartup 0x00df7fd0 int
int rdFont_bStartup;

// Line 520: rdFont_bOpen 0x00df7fd4 int
int rdFont_bOpen;

// Line 522: rdPolyline_aVerticesCache 0x00df83a0 rdVector3[4] 
rdVector3 rdPolyline_aVerticesCache[4];

// Line 524: rdParticle_aFaceVertices 0x00df8760 rdVector3[4]
rdVector3 rdParticle_aFaceVertices[4];

// Line 526: rdParticle_aTransformedVertices 0x00df8b20 rdVector3
rdVector3 rdParticle_aTransformedVertices;

// Line 528: g_hWnd 0x00dfaa28 HWND
HWND g_hWnd;

// Line 529: g_nCmdShow 0x00dfaa2c int
int g_nCmdShow;

// Line 530: g_WndProc 0x00dfaa30 Window_MSGHANDLER_ptr
Window_MSGHANDLER_ptr g_WndProc;

// Line 531: Window_border_width 0x00dfaa34 int
int Window_border_width;

// Line 532: Window_border_height 0x00dfaa38 int
int Window_border_height;

// Line 533: wuRegistry_bInitted 0x00dfaa3c int
int wuRegistry_bInitted;

// Line 534: wuRegistry_lpSubKey 0x00dfaa40 LPCSTR
LPCSTR wuRegistry_lpSubKey;

// Line 535: wuRegistry_hKey 0x00dfaa44 HKEY
HKEY wuRegistry_hKey;

// Line 541: swrModel_unk_array 0x00dfb040 swrModel_unk[4]
swrModel_unk swrModel_unk_array[4];

// Line 543: rdCamera_toggle 0x00dfb1b0 int
int rdCamera_toggle;

// Line 544: rdCamera_transform 0x00dfb1dc  rdMatrix44
rdMatrix44 rdCamera_transform;

// Line 546: rdMatrix44_unk 0x00dfb21c rdMatrix44
rdMatrix44 rdMatrix44_unk;

// Line 548: cameraFOV 0x00dfb2e0 float
float cameraFOV;

// Line 549: cameraAspectRatio 0x00dfb2e4 float
float cameraAspectRatio;

// Line 552: swrTextEntries1Text 0x00e2c380 char[128][128]
char swrTextEntries1Text[128][128];

// Line 554: frametotal 0x00e22a30 unsigned int
unsigned int frametotal;

// Line 556: timetotal 0x00e22a38 double
double timetotal;

// Line 558: swrRace_frameTimeMs 0x00e22a40 float
float swrRace_frameTimeMs;

// Line 560: swrRace_dt_raw_d 0x00e22a48 double
double swrRace_dt_raw_d;

// Line 562: swrRace_deltaTimeMs 0x00e22a50 float
float swrRace_deltaTimeMs;

// Line 564: rdMatrix44_00e25960 0x00e25960 rdMatrix44
rdMatrix44 rdMatrix44_00e25960;

// Line 566: swrRace_FireLocation 0x00e25e00 float
float swrRace_FireLocation;

// Line 568: swr_sceneModels2 0x00e29160 void*[151]
void* swr_sceneModels2[151];

// Line 570: swrRace_Transition 0x00e295a0 float
float swrRace_Transition;

// Line 572: swrRace_MenuMaxSelection 0x00e295cc int
int swrRace_MenuMaxSelection;

// Line 573: swrRace_MenuSelectedItem 0x00e295d0 int
int swrRace_MenuSelectedItem;

// Line 575: swr_sceneElmos 0x00e29600 swrObjElmo*[151]
swrObjElmo* swr_sceneElmos[151];

// Line 577: rdMatrix44_unk4 0x00e298c0 rdMatrix44
rdMatrix44 rdMatrix44_unk4;

// Line 579: swr_sceneModels 0x00e29900 void*[151]
void* swr_sceneModels[151];

// Line 581: rdMatrix44_unk8 0x00e29b60 rdMatrix44
rdMatrix44 rdMatrix44_unk8;

// Line 583: rdVector3_unk1 0x00e29b90 rdVector3
rdVector3 rdVector3_unk1;

// Line 585: swrObj_Main1 0x00e29bc0 swrObjMain[5]
swrObjMain swrObj_Main1[5];

// Line 587: rdMatrix44_unk3 0x00e2ae80 rdMatrix44
rdMatrix44 rdMatrix44_unk3;

// Line 589: rdMatrix44_unk7 0x00e2af00 rdMatrix44
rdMatrix44 rdMatrix44_unk7;

// Line 590: rdMatrix44_unk6 0x00e2af60 rdMatrix44
rdMatrix44 rdMatrix44_unk6;

// Line 591: swr_sceneAnimations 0x00e2afa0 void*[300]
void* swr_sceneAnimations[300];

// Line 593: rdVector3_unk2 0x00e2b470 rdVector3
rdVector3 rdVector3_unk2;

// Line 595: swrTextEntries2Text 0x00e303a0 char[128][128]
char swrTextEntries2Text[128][128];

// Line 596: swrTextEntries2Colors 0x00e343a0 char[128][4]
char swrTextEntries2Colors[128][4];

// Line 598: swrTextEntries2Pos 0x00e34660 short[32][2]
short swrTextEntries2Pos[32][2];

// Line 599: swrTextEntries1Pos 0x00e34860 short[128][2]
short swrTextEntries1Pos[128][2];

// Line 601: translation_unk 0x00e996c0 rdVector3
rdVector3 translation_unk;

// Line 602: rotation_unk 0x00e996cc rdVector3
rdVector3 rotation_unk;

// Line 604: GameSettingFlags 0x00e996dc int
int GameSettingFlags;

// Line 606: rdMatrix_unk7 0x00e9ba44 rdMatrix44
rdMatrix44 rdMatrix_unk7;

// Line 608: swrSprite_array 0x00e9ba60 swrSprite
swrSprite swrSprite_array;

// Line 610: sound_music_volume 0x00e364a6 short
short sound_music_volume;

// Line 612: swrRace_UnlockDataBase 0x00e35a84 int
int swrRace_UnlockDataBase;

// Line 614: swrRace_truguts 0x00e35a98 int
int swrRace_truguts;

// Line 616: swrRace_nbPitDroids 0x00e35aa0 char
char swrRace_nbPitDroids;

// Line 617: swrRace_traction_upgrade_level 0x00e35aa1 char
char swrRace_traction_upgrade_level;

// Line 618: swrRace_turning_upgrade_level 0x00e35aa2 char
char swrRace_turning_upgrade_level;

// Line 619: swrRace_acceleration_upgrade_level 0x00e35aa3 char
char swrRace_acceleration_upgrade_level;

// Line 620: swrRace_topspeed_upgrade_level 0x00e35aa4 char
char swrRace_topspeed_upgrade_level;

// Line 621: swrRace_airbrake_upgrade_level 0x00e35aa5 char
char swrRace_airbrake_upgrade_level;

// Line 622: swrRace_cooling_upgrade_level 0x00e35aa6 char
char swrRace_cooling_upgrade_level;

// Line 623: swrRace_repair_upgrade_level 0x00e35aa7 char
char swrRace_repair_upgrade_level;

// Line 624: swrRace_traction_upgrade_health 0x00e35aa8 char
char swrRace_traction_upgrade_health;

// Line 625: swrRace_turning_upgrade_health 0x00e35aa9 char
char swrRace_turning_upgrade_health;

// Line 626: swrRace_acceleration_upgrade_health 0x00e35aaa char
char swrRace_acceleration_upgrade_health;

// Line 627: swrRace_topspeed_upgrade_health 0x00e35aab char
char swrRace_topspeed_upgrade_health;

// Line 628: swrRace_airbrake_upgrade_health 0x00e35aac char
char swrRace_airbrake_upgrade_health;

// Line 629: swrRace_cooling_upgrade_health 0x00e35aad char
char swrRace_cooling_upgrade_health;

// Line 630: swrRace_repair_upgrade_health 0x00e35aae char
char swrRace_repair_upgrade_health;

// Line 632: traction_upgrade_level 0x00e364f5 char
char traction_upgrade_level;

// Line 633: turning_upgrade_level 0x00e364f6 char
char turning_upgrade_level;

// Line 634: acceleration_upgrade_level 0x00e364f7 char
char acceleration_upgrade_level;

// Line 635: topspeed_upgrade_level 0x00e364f8 char
char topspeed_upgrade_level;

// Line 636: airbrake_upgrade_level 0x00e364f9 char
char airbrake_upgrade_level;

// Line 637: cooling_upgrade_level 0x00e364fa char
char cooling_upgrade_level;

// Line 638: repair_upgrade_level 0x00e364fb char
char repair_upgrade_level;

// Line 640: rdMatrix_unk8 0x00e37480 rdMatrix44
rdMatrix44 rdMatrix_unk8;

// Line 642: rdMatrix_unk10 0x00e37520 rdMatrix44*
rdMatrix44* rdMatrix_unk10;

// Line 644: rdMatrix_unk11 0x00e3752c rdMatrix44*
rdMatrix44* rdMatrix_unk11;

// Line 646: rdMatrix44_model_MVP 0x00e37580 rdMatrix44
rdMatrix44 rdMatrix44_model_MVP;

// Line 647: rdMatrixStack34 0x00e375c0 rdMatrix34[33]
rdMatrix34 rdMatrixStack34[33];

// Line 649: rdMatrix44_ringBuffer 0x00e37c00 rdMatrix44[0xbff]
rdMatrix44 rdMatrix44_ringBuffer[0xbff];

// Line 651: texture_buffer 0x00e93860 void*[1700] 
void* texture_buffer[1700];

// Line 653: assetBufferEnd 0x00e981e4 char*
char* assetBufferEnd;

// Line 655: assetBuffer 0x00e98200 char* 
char* assetBuffer;

// Line 657: texture_count 0x00e9823c unsigned int
unsigned int texture_count;

// Line 659: rdMatrix44_stack 0x00e985c0 rdMatrix44[32]
rdMatrix44 rdMatrix44_stack[32];

// Line 661: swrRace_SelectIndex 0x00e99240 int
int swrRace_SelectIndex;

// Line 663: swrRace_PodRotationAnimation 0x00e99384 float
float swrRace_PodRotationAnimation;

// Line 665: rdMatrix44_unk2 0x00e9b9e8 rdMatrix44
rdMatrix44 rdMatrix44_unk2;

// Line 667: sound_3d_gain_adjust 0x00e9e048 float
float sound_3d_gain_adjust;

// Line 669: unk_statuses 0x00e9ed60 int[24] 
int unk_statuses[24];

// Line 670: swrScene_animations 0x00e9edc0 void*[300] 
void* swrScene_animations[300];

// Line 672: stdPlatform_hostServices 0x00e9f280 HostServices
HostServices stdPlatform_hostServices;

// Line 674: rootPathName 0x00e9f300 char[80]
char rootPathName[80];

// Line 675: unicode_unk 0x00e9f3c4 wchar_t[32]
wchar_t unicode_unk[32];

// Line 677: sithPlayer_g_aPlayers 0x00e9f448 SithPlayer[1]; 
SithPlayer sithPlayer_g_aPlayers[1];;

// Line 679: multiplayer_racer1_id 0x00ea0260 int
int multiplayer_racer1_id;

// Line 680: multiplayer_racer2_id 0x00ea0264 int
int multiplayer_racer2_id;

// Line 681: multiplayer_racer3_id 0x00ea0268 int
int multiplayer_racer3_id;

// Line 682: multiplayer_racer4_id 0x00ea026c int
int multiplayer_racer4_id;

// Line 683: multiplayer_racer5_id 0x00ea0270 int
int multiplayer_racer5_id;

// Line 684: multiplayer_racer6_id 0x00ea0274 int
int multiplayer_racer6_id;

// Line 685: multiplayer_racer7_id 0x00ea0278 int
int multiplayer_racer7_id;

// Line 686: multiplayer_racer8_id 0x00ea027c int
int multiplayer_racer8_id;

// Line 687: multiplayer_racer9_id 0x00ea0280 int
int multiplayer_racer9_id;

// Line 688: multiplayer_racer10_id 0x00ea0284 int
int multiplayer_racer10_id;

// Line 689: multiplayer_racer11_id 0x00ea0288 int
int multiplayer_racer11_id;

// Line 690: multiplayer_racer12_id 0x00ea028c int
int multiplayer_racer12_id;

// Line 691: multiplayer_racer13_id 0x00ea0290 int
int multiplayer_racer13_id;

// Line 692: multiplayer_racer14_id 0x00ea0294 int
int multiplayer_racer14_id;

// Line 693: multiplayer_racer15_id 0x00ea0298 int
int multiplayer_racer15_id;

// Line 694: multiplayer_racer16_id 0x00ea029c int
int multiplayer_racer16_id;

// Line 695: multiplayer_racer17_id 0x00ea02a0 int
int multiplayer_racer17_id;

// Line 696: multiplayer_racer18_id 0x00ea02a4 int
int multiplayer_racer18_id;

// Line 697: multiplayer_racer19_id 0x00ea02a8 int
int multiplayer_racer19_id;

// Line 698: multiplayer_racer20_id 0x00ea02ac int
int multiplayer_racer20_id;

// Line 699: multiplayer_track_select 0x00ea02b0 swrRace_TRACK
swrRace_TRACK multiplayer_track_select;

// Line 701: multiplayer_laps 0x00ea02b8 int
int multiplayer_laps;

// Line 703: swr_unk_array 0x00e27000 int[50]
int swr_unk_array[50];

// Line 705: rdMatrix44_unk5 0x00e2b3e0 rdMatrix44
rdMatrix44 rdMatrix44_unk5;

// Line 707: rdMatrix44_unk9 0x00e2b440 rdMatrix44
rdMatrix44 rdMatrix44_unk9;

// Line 708: swrTextEntries1Pos 0x00e2b480 char[128][4]
char swrTextEntries1Pos[128][4];

// Line 710: sithMulti_g_serverId 0x00ec7620 DPID
DPID sithMulti_g_serverId;

// Line 712: swrConfig_FORCE_STRENGTH 0x00ec83e0 int
int swrConfig_FORCE_STRENGTH;

// Line 713: swrConfig_FORCE_AUTOCENTER 0x00ec83e4 int
int swrConfig_FORCE_AUTOCENTER;

// Line 714: swrConfig_FORCE_COLLISIONS 0x00ec83e8 int
int swrConfig_FORCE_COLLISIONS;

// Line 715: swrConfig_FORCE_DAMAGE 0x00ec83ec int
int swrConfig_FORCE_DAMAGE;

// Line 716: swrConfig_FORCE_TERRAIN 0x00ec83f0 int
int swrConfig_FORCE_TERRAIN;

// Line 717: swrConfig_FORCE_PODACTIONS 0x00ec83f4 int
int swrConfig_FORCE_PODACTIONS;

// Line 718: swrConfig_FORCE_GFORCES 0x00ec83f8 int
int swrConfig_FORCE_GFORCES;

// Line 719: swrConfig_FORCE_ENGINERUMBLE 0x00ec83fc int
int swrConfig_FORCE_ENGINERUMBLE;

// Line 721: rdCamera_pCurCameraZfar 0x00ec8578 float
float rdCamera_pCurCameraZfar;

// Line 723: rdCamera_mat 0x00ec8580 rdMatrix34
rdMatrix34 rdCamera_mat;

// Line 725: screen_height 0x00ec85e8 int
int screen_height;

// Line 726: rdCamera_main_ptr 0x00ec85ec rdCamera*
rdCamera* rdCamera_main_ptr;

// Line 728: stdDisplayWindow_g 0x00ec85fc swrDisplayWindow
swrDisplayWindow stdDisplayWindow_g;

// Line 730: swrConfig_VIDEO_REFLECTIONS 0x00ec86a0 int
int swrConfig_VIDEO_REFLECTIONS;

// Line 731: swrConfig_VIDEO_ZEFFECTS 0x00ec86a4 int
int swrConfig_VIDEO_ZEFFECTS;

// Line 732: swrConfig_VIDEO_DYNAMIC_LIGHTING 0x00ec86a8 int
int swrConfig_VIDEO_DYNAMIC_LIGHTING;

// Line 733: swrConfig_VIDEO_VSYNC 0x00ec86ac int
int swrConfig_VIDEO_VSYNC;

// Line 734: swrConfig_VIDEO_LENSFLARE 0x00ec86b0 int
int swrConfig_VIDEO_LENSFLARE;

// Line 735: swrConfig_VIDEO_ENGINEEXHAUST 0x00ec86b4 int
int swrConfig_VIDEO_ENGINEEXHAUST;

// Line 736: swrConfig_VIDEO_TEXTURE_RES 0x00ec86b8 int
int swrConfig_VIDEO_TEXTURE_RES;

// Line 737: swrConfig_VIDEO_MODEL_DETAIL 0x00ec86bc int
int swrConfig_VIDEO_MODEL_DETAIL;

// Line 738: swrConfig_VIDEO_DRAWDISTANCE 0x00ec86c0 int
int swrConfig_VIDEO_DRAWDISTANCE;

// Line 739: screen_width 0x00ec86c4 int
int screen_width;

// Line 741: tagRect 0x00ec86d0 LECRECT
LECRECT tagRect;

// Line 743: rdCanvas_main_ptr 0x00ec86e0 rdCanvas*
rdCanvas* rdCanvas_main_ptr;

// Line 745: swrMaterialSlot_array 0x00ec8700 swrMaterialSlot*[10]
swrMaterialSlot* swrMaterialSlot_array[10];

// Line 747: g_mouse_x 0x00ec874c int
int g_mouse_x;

// Line 748: g_mouse_x2 0x00ec8750 int
int g_mouse_x2;

// Line 750: g_mouse_y 0x00ec8754 int
int g_mouse_y;

// Line 751: g_mouse_y2 0x00ec8754 int
int g_mouse_y2;

// Line 753: Deadzone 0x00ec876c float
float Deadzone;

// Line 754: swrConfig_mouseNbButtons 0x00ec8770 int
int swrConfig_mouseNbButtons;

// Line 756: swrConfig_mouseNbAxis 0x00ec878c int
int swrConfig_mouseNbAxis;

// Line 757: flip_x_axis 0x00ec8790 int
int flip_x_axis;

// Line 758: flip_y_axis 0x00ec8794 int
int flip_y_axis;

// Line 759: flip_z_axis 0x00ec8798 int
int flip_z_axis;

// Line 760: swrConfig_joystickNbButtons 0x00ec879c int
int swrConfig_joystickNbButtons;

// Line 761: swrConfig_joystickNbAxis 0x00ec87a0 int
int swrConfig_joystickNbAxis;

// Line 763: swrRace_ThrottleInput 0x00ec8830 float
float swrRace_ThrottleInput;

// Line 765: swrRace_PitchInput 0x00ec883c float
float swrRace_PitchInput;

// Line 767: swrRace_ThrustInput 0x00ec884c float
float swrRace_ThrustInput;

// Line 768: swrRace_BoostInput 0x00ec8850 float
float swrRace_BoostInput;

// Line 770: stdControl_KeyPressed_unused 0x00ec88e0 char[0x100]
char stdControl_KeyPressed_unused[0x100];

// Line 772: stdControlInputItems 0x00ec89e4 stdControlInputItem[64]
stdControlInputItem stdControlInputItems[64];

// Line 774: stdPlatfom_FPU1 0x00ec8c80 unsigned short
unsigned short stdPlatfom_FPU1;

// Line 775: stdPlatfom_FPU2 0x00ec8c82 unsigned short
unsigned short stdPlatfom_FPU2;

// Line 776: stdPlatfom_FPU3 0x00ec8c84 unsigned int
unsigned int stdPlatfom_FPU3;

// Line 778: iDirectDrawSurface4_ptr 0x00ec8d00 LPDIRECTDRAWSURFACE4
LPDIRECTDRAWSURFACE4 iDirectDrawSurface4_ptr;

// Line 779: _ddSurfaceDesc2_2 0x00ec8d04 DDSURFACEDESC2
DDSURFACEDESC2 _ddSurfaceDesc2_2;

// Line 781: directDrawVidMemTotal 0x00ec8d80 int;
int; directDrawVidMemTotal;

// Line 783: stdDisplay_g_frontBuffer 0x00ec8ca0 stdVBuffer
stdVBuffer stdDisplay_g_frontBuffer;

// Line 784: stdDisplay_g_backBuffer 0x00ec8da0 stdVBuffer
stdVBuffer stdDisplay_g_backBuffer;

// Line 789: stdConffile_g_entry 0x00ec8e80 StdConffileEntry
StdConffileEntry stdConffile_g_entry;

// Line 790: stdConffile_g_aLine 0x00ec9e84 char* 
char* stdConffile_g_aLine;

// Line 792: DirectInputJoysticks 0x00ec9ea0 void*
void* DirectInputJoysticks;

// Line 794: DirectInputJoystickGUID 0x00ec9ea4 GUID
GUID DirectInputJoystickGUID;

// Line 796: stdControlJoystickDevice 0x00eca0e4 LPDIRECTINPUTDEVICEA
LPDIRECTINPUTDEVICEA stdControlJoystickDevice;

// Line 798: DirectInputMouses 0x00ecb240 void*
void* DirectInputMouses;

// Line 800: pDIMouseDevice 0x00ecb484 LPDIRECTINPUTDEVICEA
LPDIRECTINPUTDEVICEA pDIMouseDevice;

// Line 801: diDevCaps_ptr 0x00ecb488 LPDIDEVCAPS
LPDIDEVCAPS diDevCaps_ptr;

// Line 803: std_output_buffer 0x00ecbc20 char[0x800]
char std_output_buffer[0x800];

// Line 805: stdPlatform_hostServices_ptr 0x00ecc420 HostServices*
HostServices* stdPlatform_hostServices_ptr;

// Line 806: rdroid_g_curLightingMode 0x00ecc424 RdLightMode
RdLightMode rdroid_g_curLightingMode;

// Line 807: rdroid_hostServices_ptr 0x00ecc428 HostServices*
HostServices* rdroid_hostServices_ptr;

// Line 808: rdCamera_screen_width 0x00ecc42c float
float rdCamera_screen_width;

// Line 809: rdroid_g_curGeometryMode 0x00ecc430 RdGeometryMode
RdGeometryMode rdroid_g_curGeometryMode;

// Line 811: rdroid_g_curRenderOptions 0x00ecc438 RdroidFlags
RdroidFlags rdroid_g_curRenderOptions;

// Line 813: rdCamera_camMatrix 0x00ecc440 rdMatrix34
rdMatrix34 rdCamera_camMatrix;

// Line 815: rdModel3_g_numDrawnFaces 0x00ecc470 int
int rdModel3_g_numDrawnFaces;

// Line 816: rdModel3_g_numDrawnAlphaFaces 0x00ecc474 int 
int rdModel3_g_numDrawnAlphaFaces;

// Line 820: VertexBuffer1 0x00ecc48c rdVector3*
rdVector3* VertexBuffer1;

// Line 822: VertexBuffer1_projected 0x00ecc49c rdVector3*
rdVector3* VertexBuffer1_projected;
