#ifndef MACROS_H
#define MACROS_H

#include <stdio.h>
#include <windows.h>
#include <assert.h>
#include <stdbool.h>

#ifdef _MSC_VER
#define __PRETTY_FUNCTION__ __FUNCSIG__
#endif

#ifdef __cplusplus
extern "C"
{
#endif
    extern FILE* hook_log;
#ifdef __cplusplus
}
#endif

#define HANG(msg)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
        fprintf(hook_log, "Hanging at %s, line %d, %s\n", __FILE__, __LINE__, __PRETTY_FUNCTION__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \
        fprintf(hook_log, "%s\n", msg);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
        fflush(hook_log);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
        assert(false);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    } while (0)

#ifdef DEBUG
#undef DEBUG
#define DEBUG(format, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
        fprintf(hook_log "DBG in %s %s:%d ", __FILE__, __PRETTY_FUNCTION__, __LINE__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
        fprintf(hook_logformat, __VA_ARGS__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
        fflush(hook_log);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    } while (0);
#else
#define DEBUG(format, ...)
#endif // DEBUG

#ifdef LOG
#undef LOG
#define LOG(format, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
        fprintf(hook_log, "LOG in %s %s:%d ", __FILE__, __PRETTY_FUNCTION__, __LINE__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
        fprintf(hook_log, format, __VA_ARGS__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \
        fflush(hook_log);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    } while (0);
#else
#define LOG(format, ...)
#endif // LOG

#ifndef SWAP32
#define SWAP32(value) (((((uint32_t)value) & 0xff00) | (((uint32_t)value) << 0x10) << 8) | ((((uint32_t)value) >> 0x10) | ((((uint32_t)value) & 0xff0000) >> 8)))
#endif // SWAP32

#define FLOAT_SWAP32_INPLACE(f_ptr)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
        *(uint32_t*)(f_ptr) = SWAP32(*(const uint32_t*)(f_ptr));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   \
    } while (0)

#ifndef SWAP16
#define SWAP16(value) (((uint16_t)value >> 8) | ((uint16_t)value << 8))
#endif // SWAP16

#ifndef TAG
#define TAG(str4) ((str4[0] << 24) | (str4[1] << 16) | (str4[2] << 8) | (str4[3] << 0))
#endif // TAG

#endif // MACROS_H
