#ifndef MACROS_H
#define MACROS_H

#include <stdio.h>
#include <windows.h>

#define HANG(msg)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
        printf("Hanging at %s, line %d, %s\n", __FILE__, __LINE__, __PRETTY_FUNCTION__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
        printf("%s\n", msg);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \
        while (1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
            Sleep(1000); /* Without sleep, CPU go brr */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    } while (0)

#ifdef DEBUG
#undef DEBUG
#define DEBUG(format, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
        printf("DBG in %s %s:%d ", __FILE__, __PRETTY_FUNCTION__, __LINE__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \
        printf(format, __VA_ARGS__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    } while (0);
#else
#define DEBUG(format, ...)
#endif // DEBUG

#ifdef LOG
#undef LOG
#define LOG(format, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
        printf("LOG in %s %s:%d ", __FILE__, __PRETTY_FUNCTION__, __LINE__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \
        printf(format, __VA_ARGS__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    } while (0);
#else
#define LOG(format, ...)
#endif // LOG

#ifndef SWAP32
#define SWAP32(value) (((((uint32_t)value) & 0xff00) | (((uint32_t)value) << 0x10) << 8) | ((((uint32_t)value) >> 0x10) | ((((uint32_t)value) & 0xff0000) >> 8)))
#endif // SWAP32

#define FLOAT_SWAP32_INPLACE(f_ptr)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
        *(uint32_t*)(f_ptr) = SWAP32(*(const uint32_t*)(f_ptr));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   \
    } while (0)

#ifndef SWAP16
#define SWAP16(value) (((uint16_t)value >> 8) | ((uint16_t)value << 8))
#endif // SWAP16

#ifndef TAG
#define TAG(str4) ((uint32_t)str4 | (((uint32_t)str4 & 0xFF0000) << 8) | (((uint32_t)str4 & 0xFF00) << 16) | (((uint32_t)str4 & 0xFF) << 24))
#endif // TAG

#endif // MACROS_H
